name: Deploy Docker Registry

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Docker Registry Directory on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ~/docker-registry"

      - name: Upload Configuration Files and Scripts
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml nginx.conf scripts/*.sh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/docker-registry/

      - name: Make Scripts Executable
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "chmod +x ~/docker-registry/scripts/*.sh"

      - name: Install Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "~/docker-registry/scripts/install_dependencies.sh"

      - name: Deploy Docker Registry
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "~/docker-registry/scripts/deploy_registry.sh '${{ secrets.REGISTRY_USERNAME }}' '${{ secrets.REGISTRY_PASSWORD }}'"

      - name: Setup SSL
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "~/docker-registry/scripts/setup_ssl.sh '${{ secrets.REGISTRY_DOMAIN }}' '${{ secrets.EMAIL }}'"
