name: Deploy and Test Docker Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Registry
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      REGISTRY_DIR: ~/docker-registry
    secrets:
      EMAIL: ${{ secrets.EMAIL }}
      REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
      USE_SSL: ${{ secrets.USE_SSL }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  test:
    name: Test Docker Registry
    needs: deploy
    uses: ./.github/workflows/reusable-test.yml
    secrets:
      REGISTRY_URL: ${{ secrets.REGISTRY_DOMAIN }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
