name: Deploy Docker Registry

on:
  workflow_call:
    inputs:
      REGISTRY_DOMAIN:
        description: 'Domain for the Docker registry'
        required: false
        type: string
      VPS_IP:
        description: 'IP address of the VPS'
        required: true
        type: string
      REGISTRY_DIR:
        description: 'Directory path for Docker registry on VPS'
        required: true
        type: string
      EMAIL:
        description: 'Email for Certbot notifications'
        required: true
        type: string
      USE_SSL:
        description: 'Whether to use SSL (true/false)'
        required: true
        type: boolean
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  DeployRegistry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Docker Registry Directory and Scripts Subdirectory on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ${{ env.REGISTRY_DIR }}"

      - name: Verify Docker Registry and Scripts Directory Exists
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "ls -ld ${{ env.REGISTRY_DIR }}"

      - name: Upload Configuration Files and Scripts
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml nginx-with-domain.conf.template nginx-without-domain.conf.template scripts/*.sh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.REGISTRY_DIR }}

      - name: Verify Uploaded Scripts and Config Files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "ls -la ${{ env.REGISTRY_DIR }}"

      - name: Make Scripts Executable
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "chmod +x ${{ env.REGISTRY_DIR }}/*.sh"

      - name: Install Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "${{ env.REGISTRY_DIR }}/install_dependencies.sh"

      - name: Deploy Docker Registry
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "${{ env.REGISTRY_DIR }}/deploy_registry.sh '${{ secrets.REGISTRY_USERNAME }}' '${{ secrets.REGISTRY_PASSWORD }}' '${{ env.REGISTRY_DIR }}'"

      - name: Configure Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "${{ env.REGISTRY_DIR }}/configure_nginx.sh '${{ env.REGISTRY_DOMAIN }}' '${{ secrets.VPS_HOST }}' '${{ env.REGISTRY_DIR }}' '${{ env.EMAIL}}'"

      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "systemctl restart nginx"
