name: Test Docker Registry

on:
  workflow_run:
    workflows: ["Deploy Docker Registry"]
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  test-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag Hello-World Image
        run: |
          docker pull hello-world:latest
          docker tag hello-world:latest ${{ secrets.REGISTRY_DOMAIN }}/test/hello-world:latest

      - name: Push Test Image to Registry
        run: |
          docker push ${{ secrets.REGISTRY_DOMAIN }}/test/hello-world:latest

      - name: Pull Test Image from Registry
        run: |
          docker pull ${{ secrets.REGISTRY_DOMAIN }}/test/hello-world:latest

      - name: Verify Image Integrity
        run: |
          # Compare image digests to ensure integrity
          PUSH_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_DOMAIN }}/test/hello-world:latest | awk -F'@' '{print $2}')
          PULL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' hello-world:latest | awk -F'@' '{print $2}')

          echo "Pushed Image Digest: $PUSH_DIGEST"
          echo "Pulled Image Digest: $PULL_DIGEST"

          if [ "$PUSH_DIGEST" != "$PULL_DIGEST" ]; then
            echo "Image digests do not match. Integrity check failed."
            exit 1
          else
            echo "Image integrity verified successfully."
          fi
